fix(seeder): Grant KMS actions for Table
cloudcomponents/cdk-constructs pull request #99
Opened 2021-05-06 02:04 UTC by liveFreeOrCode

If a table has a customer managed encryption key, the singleton handler needs to be given the appropriate KMS authorization as deemed necessary by:
https://docs.aws.amazon.com/kms/latest/developerguide/services-dynamodb.html\#dynamodb-authz

Fixes #98

2021-05-06 07:30 UTC, hupe1980 requested changes

2021-05-06 11:24 UTC, liveFreeOrCode commented on packages/cdk-dynamodb-seeder/src/dynamodb-seeder.ts
> +          actions: ['kms:Encrypt', 'kms:Decrypt', 'kms:ReEncrypt*', 'kms:GenerateDataKey*', 'kms:DescribeKey', 'kms:CreateGrant'],
I had originally thought the same thing, but If you scroll down in the link I posted to `Customer managed CMK key policy`, you'll see the following:

> At a minimum, DynamoDB requires the following permissions on a customer managed CMK:
> - kms:Encrypt
> - kms:Decrypt
> - kms:ReEncrypt* (for kms:ReEncryptFrom and kms:ReEncryptTo)
> - kms:GenerateDataKey* (for kms:GenerateDataKey and kms:GenerateDataKeyWithoutPlaintext)
> - kms:DescribeKey
> - kms:CreateGrant

2021-05-06 12:18 UTC, liveFreeOrCode commented on packages/cdk-dynamodb-seeder/src/dynamodb-seeder.ts
> +          actions: ['kms:Encrypt', 'kms:Decrypt', 'kms:ReEncrypt*', 'kms:GenerateDataKey*', 'kms:DescribeKey', 'kms:CreateGrant'],
For some additional context, I also tested another library, that [adds those 3 actions](https://github.com/elegantdevelopment/aws-cdk-dynamodb-seeder/blob/ec1d681e1ffdf5f1f72584f18cd445019aa891e4/lib/index.ts#L110) that you mentioned, and it was giving me the same KMS authorization errors.  Ultimately, I liked this library more :)

2021-05-09 12:56 UTC, hupe1980 approved these changes
LGTM! Thx

2021-05-09 12:57 UTC, merged